module.exports = {
    data: [ { job: 'Software Engineer Intern',
    company: 'Elation Health',
    location: 'San Francisco, CA, US',
    postDateRaw: '13d',
    postDate: '',
    source: 'linkedin',
    desc: 'Since inception, we’ve been focused on building a delightful world-class experience that empowers physicians to deliver phenomenal care to patients. We grow when you grow. grnh.se',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAgjAAAAJGIxZjg3Y2JkLTc5NmYtNDVmOS05NzgyLWI2ZDk5NGYyYWQ3Ng.png',
    detailUrl: 'Software Engineer Intern' },
  { job: 'Internship – Software Engineer',
    company: 'Sentient Science',
    location: 'Buffalo, NY, US',
    postDateRaw: '12d',
    postDate: '',
    source: 'linkedin',
    desc: 'We are seeking a highly motivated intern to help us develop scalable software that can automate new and existing data-driven processes. sentientscience.applytojob.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAMgAAAAJGVmOTc5NjRiLTA4NmUtNDNkMC05YWY4LTJhMzMwYzFiMjcwYQ.png',
    detailUrl: 'Internship – Software Engineer' },
  { job: 'Automation Software Engineer Internship - CO7235693',
    company: 'seagate',
    location: 'Longmont, CO, US',
    postDateRaw: '5d',
    postDate: '',
    source: 'linkedin',
    desc: 'We are seeking an Automation SoftwareEngineer Intern to join our design center team in Longmont, COAbout our Team:As part of Seagate\'s commitment to excellence, we have ... my.jobs',
    identifier: '',
    logoUrl: '/scds/common/u/images/themes/katy/ghosts/company/ghost_company_80x80_v1.png',
    detailUrl: 'Automation Software Engineer Internship - CO7235693' },
  { job: 'Software Engineering Intern',
    company: 'RevolutionParts, Inc.',
    location: 'Phoenix, AZ, US',
    postDateRaw: '4d',
    postDate: '',
    source: 'linkedin',
    desc: 'We’re looking for a software engineering intern to join our team. High level of self-management and organizational skills. Great written and oral communication skills. jsco.re',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAOHAAAAJGI5MDFjOTMxLWFmMjktNGRmZC05MzRhLTM2NGI0Yzk3M2U5Mw.png',
    detailUrl: 'Software Engineering Intern' },
  { job: 'Freshman Software Engineering Internship',
    company: 'Two Sigma',
    location: 'Houston, TX, US',
    postDateRaw: '2d',
    postDate: '',
    source: 'linkedin',
    desc: 'You will work with Two Sigma employees and other interns on software engineering projects, receiving technical training and mentorship to help you deliver professional software ... careers.twosigma.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAOtAAAAJDg1NjRkMjdhLTU5YTktNDc3OC05Mzg5LWNhYjk0YjBiYjE2NQ.png',
    detailUrl: 'Freshman Software Engineering Internship' },
  { job: 'Software Developer / IT Engineer / Security Analyst Internship',
    company: 'COUNTRY Financial®',
    location: 'Bloomington, MN, US',
    postDateRaw: 'NEW',
    postDate: '',
    source: 'linkedin',
    desc: 'Interns will work with a project team, intern mentor and information technology management to gain valuable experience, and develop leadership, technical, analytical, ... ccservices.taleo.net',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAPkAAAAJDNlNmI0MzYwLWZmNWQtNDMzYS05NWVjLWFiZGU1MGI2NWYzMw.png',
    detailUrl: 'Software Developer / IT Engineer / Security Analyst Internship' },
  { job: 'Spring Software Developer / Engineer Internship',
    company: 'Braxton Science & Technology Group',
    location: 'Colorado Springs, CO, US',
    postDateRaw: '25d',
    postDate: '',
    source: 'linkedin',
    desc: 'We are seeking a self-starter, who is a collaborator and has strong software development skills. Experience in computer science, software engineering or related discipline. jobs.bstgllc.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/p/6/005/0b0/22b/3253e98.png',
    detailUrl: 'Spring Software Developer / Engineer Internship' },
  { job: 'Data Software Engineer Intern Summer 2018',
    company: 'MailChimp',
    location: 'Atlanta, GA, US',
    postDateRaw: '2d',
    postDate: '',
    source: 'linkedin',
    desc: 'We\'re looking for an intern to create systems and products that use all of that data. Experience working with external APIs. boards.greenhouse.io',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAc5AAAAJGU0MjZiMzFhLTYwZTQtNDZhOC05YWNkLWI4YzJjZmIwYjNjMA.png',
    detailUrl: 'Data Software Engineer Intern Summer 2018' },
  { job: 'Software Engineer Internship',
    company: 'Braintree',
    location: 'Chicago, IL, US',
    postDateRaw: '35d',
    postDate: '',
    source: 'linkedin',
    desc: 'We are looking for smart, tenacious, and outgoing individuals who are looking to challenge themselves and for a highly collaborative environment. app.greenhouse.io',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAxgAAAAJDYwMGIyZWJiLTA1YjItNDUxZC04NDAxLWI2NjczOWY5MTY1Nw.png',
    detailUrl: 'Software Engineer Internship' },
  { job: 'Software Engineering Intern (Summer 2018)',
    company: 'Automated Insights',
    location: 'Durham, NC, US',
    postDateRaw: '25d',
    postDate: '',
    source: 'linkedin',
    desc: 'As a Software Engineer Intern, you will be a full member of our teams; you will participate in project meetings, present results to company stakeholders, and produce as much as ... automatedinsights.applytojob.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAQMAAAAJGZlOGI4MDk0LTAxMTctNDBkMy04ZWIyLTE4ZjY0N2IwNGFhMw.png',
    detailUrl: 'Software Engineering Intern (Summer 2018)' },
  { job: '2018 Amazon Future Engineer Summer Internship - Software Development Engineer',
    company: 'Amazon',
    location: 'Seattle, WA, US',
    postDateRaw: '24d',
    postDate: '',
    source: 'linkedin',
    desc: 'Our AFE interns will partner with experienced software development engineers, who both help and challenge them as they work on projects that matter to our customers. us-amazon.icims.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAA0ZAAAAJDk1ZjA0ZTJmLWQwYWQtNDEwNS04M2QxLTIwM2UxMTE0NTBkMw.png',
    detailUrl: '2018 Amazon Future Engineer Summer Internship - Software Development Engineer' },
  { job: 'Senior Software Engineer, Internal Tools',
    company: 'Lyft',
    location: 'San Francisco, CA, US',
    postDateRaw: '9d',
    postDate: '',
    source: 'linkedin',
    desc: 'This team collaborates with a wide variety of internal stakeholders in the Customer Experience organization to deliver our work to a large, diverse, geographically distributed ... jobs.lever.co',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAitAAAAJDBkOTkzMjc3LTJmNmQtNGM2Ni1iNmNjLWRhYmJhZWQzYjdhMQ.png',
    detailUrl: 'Senior Software Engineer, Internal Tools' },
  { job: 'Software Engineering Internship - Undergraduate',
    company: 'FactSet',
    location: 'Austin, TX, US',
    postDateRaw: 'NEW',
    postDate: '',
    source: 'linkedin',
    desc: 'During your 12 week internship, you\'ll work on a project that personally interests you, while building your skills and relationships. disabledperson.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAeIAAAAJGU1YmZlNGFkLTgyOTctNGIxNS1iZGJiLTRlN2ZiMGZiMWU5OQ.png',
    detailUrl: 'Software Engineering Internship - Undergraduate' },
  { job: 'Software Engineer - Internship',
    company: 'Netsmart',
    location: 'Great River, NY, US',
    postDateRaw: 'NEW',
    postDate: '',
    source: 'linkedin',
    desc: 'Demonstrates achievement in academics, internships, co-ops, or other work experience. FUTURES experience what makes growing a career at Netsmart special….building. netsmart.jobs.net',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAIA_wDGAAAAAQAAAAAAAAtVAAAAJGUyMDkyZDMxLTU5NjktNDc2Yy1hOGM2LTc0NzExYzBmMGNjNQ.png',
    detailUrl: 'Software Engineer - Internship' },
  { job: 'Software Engineer Internship - Platform',
    company: 'Descartes Labs',
    location: 'Santa Fe, NM, US',
    postDateRaw: '3d',
    postDate: '',
    source: 'linkedin',
    desc: 'We are looking for a qualified and eager-to-learn Platform Engineering Intern to be a part of our team for the summer! Some experience with a compiled language (C, C++, etc...) jobs.lever.co',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAANJAAAAJDNlNDI4NGY3LWFmMWUtNDgyZS04N2U3LWM3N2RkOTk3OGMzNQ.png',
    detailUrl: 'Software Engineer Internship - Platform' },
  { job: 'Internship: Software Engineering | Summer 2018',
    company: 'Cognex Corporation',
    location: 'Natick, MA, US',
    postDateRaw: 'NEW',
    postDate: '',
    source: 'linkedin',
    desc: 'The Deep Learning, Core Vision, and 3D Technology teams are seeking talented summer or fall interns who bring creative vision problem solving and solid software engineering to ... chm.tbe.taleo.net',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/p/3/000/110/3f0/156828f.png',
    detailUrl: 'Internship: Software Engineering | Summer 2018' },
  { job: 'Software Engineer - Intern',
    company: 'Blend',
    location: 'San Francisco, CA, US',
    postDateRaw: '16d',
    postDate: '',
    source: 'linkedin',
    desc: 'We’re looking for talented software engineering interns to join our diverse and fast-growing engineering team. Excellent coding, problem solving, and debugging skills. jobs.lever.co',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAA1nAAAAJDU5YTlkMTczLTVmYWYtNGNmYy1hM2U2LTJlZjU5MmFiNDg0Nw.png',
    detailUrl: 'Software Engineer - Intern' },
  { job: 'Software Engineering Internship, Studios - Summer 2018',
    company: 'The Walt Disney Studios',
    location: 'Burbank, CA, US',
    postDateRaw: '26d',
    postDate: '',
    source: 'linkedin',
    desc: 'Uniting each endeavor is a commitment to creating and delivering unforgettable experiences — and we’re constantly looking for new ways to enhance these exciting experiences. jobs.disneycareers.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/p/3/000/126/3bb/2e0e7a1.png',
    detailUrl: 'Software Engineering Internship, Studios - Summer 2018' },
  { job: 'DevOps Software Engineering Internship',
    company: 'Red Hat',
    location: 'Westford, MA, US',
    postDateRaw: '2d',
    postDate: '',
    source: 'linkedin',
    desc: 'The Red Hat DevOps team is looking for a Software Engineering Intern to join us in Westford, MA. us-redhat.icims.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAhyAAAAJDhlZDY0MmY5LTlkMzItNDEyMy1iZWM3LTgyYTgzNjY1NmRhYg.png',
    detailUrl: 'DevOps Software Engineering Internship' },
  { job: 'Summer College Intern - Software EngineeringSummer College Intern - Software Engineering',
    company: 'Florida Power & Light Company',
    location: 'Saint Paul, MN, US',
    postDateRaw: '21d',
    postDate: '',
    source: 'linkedin',
    desc: 'The internship will provide mentoring and practical hands-on experience in a corporate setting, and exposure to business unit activities, leadership and culture (e.g., staff ... neuvoo.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAASzAAAAJDQyNjMyMzlkLTI0OTgtNGZlYS1hNzMxLWIyZmQ2NGQ3ZWE5Mg.png',
    detailUrl: 'Summer College Intern - Software EngineeringSummer College Intern - Software Engineering' },
  { job: 'Software Engineering Internship - Summer 2018',
    company: 'Knewton',
    location: 'New York City, NY, US',
    postDateRaw: '11d',
    postDate: '',
    source: 'linkedin',
    desc: 'At Knewton, interns are a key part of the team who work hand in hand with a development team working at the cutting edge of education software. jobs.lever.co',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAIA_wDGAAAAAQAAAAAAAAxKAAAAJGRhZGQwODhlLWQ4YzQtNDEyYS04ZGI0LTI3MTliMWE5YTZjMw.png',
    detailUrl: 'Software Engineering Internship - Summer 2018' },
  { job: 'Digital Media Software Engineering Internship, DATG (CA) - Summer 2018',
    company: 'The Walt Disney Company',
    location: 'Burbank, CA, US',
    postDateRaw: '27d',
    postDate: '',
    source: 'linkedin',
    desc: 'Our ideal candidate is creative, energetic and has a desire to learn leading edge technologies and has a passion for demonstrating skill and precision in his/her work. jobs.disneycareers.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAA1IAAAAJGE1MjRhZmQyLWE5N2QtNDUyMC04MWM5LTg5NTNlMjhmYjlmZA.png',
    detailUrl: 'Digital Media Software Engineering Internship, DATG (CA) - Summer 2018' },
  { job: 'Software Development Engineer - Internship',
    company: 'Audible, Inc.',
    location: 'Newark, NJ, US',
    postDateRaw: '24d',
    postDate: '',
    source: 'linkedin',
    desc: 'Proven experience as an innovator and a creator, with strong critical thinking and communication skills. We have internships in Newark, NJ, Cambridge, MA, and Seattle, WA. us-amazon.icims.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAANjAAAAJDk2ZGE4YzBkLTY3ODktNGM1YS1iNTQxLTgwMDg5ZThmZjdkZA.png',
    detailUrl: 'Software Development Engineer - Internship' },
  { job: 'Software Engineer- 2018 Summer internship',
    company: 'Motorola Solutions',
    location: 'Chicago, Illinois',
    postDateRaw: '21d',
    postDate: '',
    source: 'linkedin',
    desc: 'Seeking local candidates who are strong in   Server-side web development using Node Js. Experience defining and building Web (REST) APIs for internal and external usage.',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAUXAAAAJGFiZTYwZDVmLTM0NDYtNDM1Mi1iN2NlLTY3MmExY2M2MmIxZg.png',
    detailUrl: 'Software Engineer- 2018 Summer internship' },
  { job: 'INTERN Software Engineer/Computer Engineer',
    company: 'Raven Industries',
    location: 'Austin, TX, US',
    postDateRaw: '19d',
    postDate: '',
    source: 'linkedin',
    desc: 'Raven Industries is currently seeking a Software/Computer Engineer Intern for our facility in Austin, TX. Complete specified projects and tasks within internship or co-op period. neuvoo.com',
    identifier: '',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAgAAAAAJDcyZGFkNjg1LWNhNzQtNGU0NS1hZjRmLTNlNGQ0MDg0MGEwMw.png',
    detailUrl: 'INTERN Software Engineer/Computer Engineer' } ]
[ { job: 'Software Engineer Intern',
    company: 'Elation Health',
    location: 'San Francisco, CA, US',
    postDateRaw: '13d',
    postDate: 2017-12-21T22:51:24.643Z,
    source: 'linkedin',
    desc: 'Since inception, we’ve been focused on building a delightful world-class experience that empowers physicians to deliver phenomenal care to patients. We grow when you grow. grnh.se',
    identifier: '01dc9c02d6a14867856b200ae08fdbdb',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAgjAAAAJGIxZjg3Y2JkLTc5NmYtNDVmOS05NzgyLWI2ZDk5NGYyYWQ3Ng.png',
    detailUrl: 'Software Engineer Intern' },
  { job: 'Internship – Software Engineer',
    company: 'Sentient Science',
    location: 'Buffalo, NY, US',
    postDateRaw: '12d',
    postDate: 2017-12-22T22:51:24.643Z,
    source: 'linkedin',
    desc: 'We are seeking a highly motivated intern to help us develop scalable software that can automate new and existing data-driven processes. sentientscience.applytojob.com',
    identifier: '4b72016b68435ec5728315395ef0953c',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAMgAAAAJGVmOTc5NjRiLTA4NmUtNDNkMC05YWY4LTJhMzMwYzFiMjcwYQ.png',
    detailUrl: 'Internship – Software Engineer' },
  { job: 'Automation Software Engineer Internship - CO7235693',
    company: 'seagate',
    location: 'Longmont, CO, US',
    postDateRaw: '5d',
    postDate: 2017-12-29T22:51:24.644Z,
    source: 'linkedin',
    desc: 'We are seeking an Automation SoftwareEngineer Intern to join our design center team in Longmont, COAbout our Team:As part of Seagate\'s commitment to excellence, we have ... my.jobs',
    identifier: 'cdbb071c7962efbe652ca1fdcc11fd06',
    logoUrl: '/scds/common/u/images/themes/katy/ghosts/company/ghost_company_80x80_v1.png',
    detailUrl: 'Automation Software Engineer Internship - CO7235693' },
  { job: 'Software Engineering Intern',
    company: 'RevolutionParts, Inc.',
    location: 'Phoenix, AZ, US',
    postDateRaw: '4d',
    postDate: 2017-12-30T22:51:24.644Z,
    source: 'linkedin',
    desc: 'We’re looking for a software engineering intern to join our team. High level of self-management and organizational skills. Great written and oral communication skills. jsco.re',
    identifier: '47c46356246dfe479b7c9f3d71ad5229',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAOHAAAAJGI5MDFjOTMxLWFmMjktNGRmZC05MzRhLTM2NGI0Yzk3M2U5Mw.png',
    detailUrl: 'Software Engineering Intern' },
  { job: 'Freshman Software Engineering Internship',
    company: 'Two Sigma',
    location: 'Houston, TX, US',
    postDateRaw: '2d',
    postDate: 2018-01-01T22:51:24.644Z,
    source: 'linkedin',
    desc: 'You will work with Two Sigma employees and other interns on software engineering projects, receiving technical training and mentorship to help you deliver professional software ... careers.twosigma.com',
    identifier: 'aa655f5db0e41d30d32ef022978e20b3',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAOtAAAAJDg1NjRkMjdhLTU5YTktNDc3OC05Mzg5LWNhYjk0YjBiYjE2NQ.png',
    detailUrl: 'Freshman Software Engineering Internship' },
  { job: 'Software Developer / IT Engineer / Security Analyst Internship',
    company: 'COUNTRY Financial®',
    location: 'Bloomington, MN, US',
    postDateRaw: 'NEW',
    postDate: 2018-01-02T22:51:24.644Z,
    source: 'linkedin',
    desc: 'Interns will work with a project team, intern mentor and information technology management to gain valuable experience, and develop leadership, technical, analytical, ... ccservices.taleo.net',
    identifier: '5138aff358ae9acc44a05131e30a6200',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAPkAAAAJDNlNmI0MzYwLWZmNWQtNDMzYS05NWVjLWFiZGU1MGI2NWYzMw.png',
    detailUrl: 'Software Developer / IT Engineer / Security Analyst Internship' },
  { job: 'Spring Software Developer / Engineer Internship',
    company: 'Braxton Science & Technology Group',
    location: 'Colorado Springs, CO, US',
    postDateRaw: '25d',
    postDate: 2017-12-09T22:51:24.644Z,
    source: 'linkedin',
    desc: 'We are seeking a self-starter, who is a collaborator and has strong software development skills. Experience in computer science, software engineering or related discipline. jobs.bstgllc.com',
    identifier: 'd261d3b303c285ced0c85100f891c285',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/p/6/005/0b0/22b/3253e98.png',
    detailUrl: 'Spring Software Developer / Engineer Internship' },
  { job: 'Data Software Engineer Intern Summer 2018',
    company: 'MailChimp',
    location: 'Atlanta, GA, US',
    postDateRaw: '2d',
    postDate: 2018-01-01T22:51:24.644Z,
    source: 'linkedin',
    desc: 'We\'re looking for an intern to create systems and products that use all of that data. Experience working with external APIs. boards.greenhouse.io',
    identifier: '59803fd5ff1b0471b3d930a0cc2d2c11',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAc5AAAAJGU0MjZiMzFhLTYwZTQtNDZhOC05YWNkLWI4YzJjZmIwYjNjMA.png',
    detailUrl: 'Data Software Engineer Intern Summer 2018' },
  { job: 'Software Engineer Internship',
    company: 'Braintree',
    location: 'Chicago, IL, US',
    postDateRaw: '35d',
    postDate: 2017-11-29T22:51:24.644Z,
    source: 'linkedin',
    desc: 'We are looking for smart, tenacious, and outgoing individuals who are looking to challenge themselves and for a highly collaborative environment. app.greenhouse.io',
    identifier: 'ca96c818219cc7e59a3a4e9421a41032',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAxgAAAAJDYwMGIyZWJiLTA1YjItNDUxZC04NDAxLWI2NjczOWY5MTY1Nw.png',
    detailUrl: 'Software Engineer Internship' },
  { job: 'Software Engineering Intern (Summer 2018)',
    company: 'Automated Insights',
    location: 'Durham, NC, US',
    postDateRaw: '25d',
    postDate: 2017-12-09T22:51:24.644Z,
    source: 'linkedin',
    desc: 'As a Software Engineer Intern, you will be a full member of our teams; you will participate in project meetings, present results to company stakeholders, and produce as much as ... automatedinsights.applytojob.com',
    identifier: 'fd7cb6de245bb91dcda143b4eb401b7a',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAQMAAAAJGZlOGI4MDk0LTAxMTctNDBkMy04ZWIyLTE4ZjY0N2IwNGFhMw.png',
    detailUrl: 'Software Engineering Intern (Summer 2018)' },
  { job: '2018 Amazon Future Engineer Summer Internship - Software Development Engineer',
    company: 'Amazon',
    location: 'Seattle, WA, US',
    postDateRaw: '24d',
    postDate: 2017-12-10T22:51:24.644Z,
    source: 'linkedin',
    desc: 'Our AFE interns will partner with experienced software development engineers, who both help and challenge them as they work on projects that matter to our customers. us-amazon.icims.com',
    identifier: '2b0478881b6803b965651aa94bede036',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAA0ZAAAAJDk1ZjA0ZTJmLWQwYWQtNDEwNS04M2QxLTIwM2UxMTE0NTBkMw.png',
    detailUrl: '2018 Amazon Future Engineer Summer Internship - Software Development Engineer' },
  { job: 'Senior Software Engineer, Internal Tools',
    company: 'Lyft',
    location: 'San Francisco, CA, US',
    postDateRaw: '9d',
    postDate: 2017-12-25T22:51:24.644Z,
    source: 'linkedin',
    desc: 'This team collaborates with a wide variety of internal stakeholders in the Customer Experience organization to deliver our work to a large, diverse, geographically distributed ... jobs.lever.co',
    identifier: 'c7aaa975faf412102dcf16b8ba0cf6b4',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAitAAAAJDBkOTkzMjc3LTJmNmQtNGM2Ni1iNmNjLWRhYmJhZWQzYjdhMQ.png',
    detailUrl: 'Senior Software Engineer, Internal Tools' },
  { job: 'Software Engineering Internship - Undergraduate',
    company: 'FactSet',
    location: 'Austin, TX, US',
    postDateRaw: 'NEW',
    postDate: 2018-01-02T22:51:24.644Z,
    source: 'linkedin',
    desc: 'During your 12 week internship, you\'ll work on a project that personally interests you, while building your skills and relationships. disabledperson.com',
    identifier: '82757048c5a28533a6199e79fe537377',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAeIAAAAJGU1YmZlNGFkLTgyOTctNGIxNS1iZGJiLTRlN2ZiMGZiMWU5OQ.png',
    detailUrl: 'Software Engineering Internship - Undergraduate' },
  { job: 'Software Engineer - Internship',
    company: 'Netsmart',
    location: 'Great River, NY, US',
    postDateRaw: 'NEW',
    postDate: 2018-01-02T22:51:24.644Z,
    source: 'linkedin',
    desc: 'Demonstrates achievement in academics, internships, co-ops, or other work experience. FUTURES experience what makes growing a career at Netsmart special….building. netsmart.jobs.net',
    identifier: '817861f37f9c205b4f5abbb20aeffc60',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAIA_wDGAAAAAQAAAAAAAAtVAAAAJGUyMDkyZDMxLTU5NjktNDc2Yy1hOGM2LTc0NzExYzBmMGNjNQ.png',
    detailUrl: 'Software Engineer - Internship' },
  { job: 'Software Engineer Internship - Platform',
    company: 'Descartes Labs',
    location: 'Santa Fe, NM, US',
    postDateRaw: '3d',
    postDate: 2017-12-31T22:51:24.644Z,
    source: 'linkedin',
    desc: 'We are looking for a qualified and eager-to-learn Platform Engineering Intern to be a part of our team for the summer! Some experience with a compiled language (C, C++, etc...) jobs.lever.co',
    identifier: '46a79f6d95945762e4f3b050a5f92f47',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAANJAAAAJDNlNDI4NGY3LWFmMWUtNDgyZS04N2U3LWM3N2RkOTk3OGMzNQ.png',
    detailUrl: 'Software Engineer Internship - Platform' },
  { job: 'Internship: Software Engineering | Summer 2018',
    company: 'Cognex Corporation',
    location: 'Natick, MA, US',
    postDateRaw: 'NEW',
    postDate: 2018-01-02T22:51:24.644Z,
    source: 'linkedin',
    desc: 'The Deep Learning, Core Vision, and 3D Technology teams are seeking talented summer or fall interns who bring creative vision problem solving and solid software engineering to ... chm.tbe.taleo.net',
    identifier: '418421f3f25d169b36fbeaaed3c77886',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/p/3/000/110/3f0/156828f.png',
    detailUrl: 'Internship: Software Engineering | Summer 2018' },
  { job: 'Software Engineer - Intern',
    company: 'Blend',
    location: 'San Francisco, CA, US',
    postDateRaw: '16d',
    postDate: 2017-12-18T22:51:24.644Z,
    source: 'linkedin',
    desc: 'We’re looking for talented software engineering interns to join our diverse and fast-growing engineering team. Excellent coding, problem solving, and debugging skills. jobs.lever.co',
    identifier: '5de98fe872fdd21ab4b52420515c5f28',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAA1nAAAAJDU5YTlkMTczLTVmYWYtNGNmYy1hM2U2LTJlZjU5MmFiNDg0Nw.png',
    detailUrl: 'Software Engineer - Intern' },
  { job: 'Software Engineering Internship, Studios - Summer 2018',
    company: 'The Walt Disney Studios',
    location: 'Burbank, CA, US',
    postDateRaw: '26d',
    postDate: 2017-12-08T22:51:24.644Z,
    source: 'linkedin',
    desc: 'Uniting each endeavor is a commitment to creating and delivering unforgettable experiences — and we’re constantly looking for new ways to enhance these exciting experiences. jobs.disneycareers.com',
    identifier: '67c74f853dd046c6f69488b5e5520f19',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/p/3/000/126/3bb/2e0e7a1.png',
    detailUrl: 'Software Engineering Internship, Studios - Summer 2018' },
  { job: 'DevOps Software Engineering Internship',
    company: 'Red Hat',
    location: 'Westford, MA, US',
    postDateRaw: '2d',
    postDate: 2018-01-01T22:51:24.644Z,
    source: 'linkedin',
    desc: 'The Red Hat DevOps team is looking for a Software Engineering Intern to join us in Westford, MA. us-redhat.icims.com',
    identifier: '8ab68ec7262038bc940591269a9dd32e',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAhyAAAAJDhlZDY0MmY5LTlkMzItNDEyMy1iZWM3LTgyYTgzNjY1NmRhYg.png',
    detailUrl: 'DevOps Software Engineering Internship' },
  { job: 'Summer College Intern - Software EngineeringSummer College Intern - Software Engineering',
    company: 'Florida Power & Light Company',
    location: 'Saint Paul, MN, US',
    postDateRaw: '21d',
    postDate: 2017-12-13T22:51:24.644Z,
    source: 'linkedin',
    desc: 'The internship will provide mentoring and practical hands-on experience in a corporate setting, and exposure to business unit activities, leadership and culture (e.g., staff ... neuvoo.com',
    identifier: '05fd4de328c0f91754e7c17b3e5cff66',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAASzAAAAJDQyNjMyMzlkLTI0OTgtNGZlYS1hNzMxLWIyZmQ2NGQ3ZWE5Mg.png',
    detailUrl: 'Summer College Intern - Software EngineeringSummer College Intern - Software Engineering' },
  { job: 'Software Engineering Internship - Summer 2018',
    company: 'Knewton',
    location: 'New York City, NY, US',
    postDateRaw: '11d',
    postDate: 2017-12-23T22:51:24.644Z,
    source: 'linkedin',
    desc: 'At Knewton, interns are a key part of the team who work hand in hand with a development team working at the cutting edge of education software. jobs.lever.co',
    identifier: 'e6eefb475415b760d785c374ffef8886',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAIA_wDGAAAAAQAAAAAAAAxKAAAAJGRhZGQwODhlLWQ4YzQtNDEyYS04ZGI0LTI3MTliMWE5YTZjMw.png',
    detailUrl: 'Software Engineering Internship - Summer 2018' },
  { job: 'Digital Media Software Engineering Internship, DATG (CA) - Summer 2018',
    company: 'The Walt Disney Company',
    location: 'Burbank, CA, US',
    postDateRaw: '27d',
    postDate: 2017-12-07T22:51:24.644Z,
    source: 'linkedin',
    desc: 'Our ideal candidate is creative, energetic and has a desire to learn leading edge technologies and has a passion for demonstrating skill and precision in his/her work. jobs.disneycareers.com',
    identifier: 'fc9fa0b0142c6d6481ec1faa62e40bdd',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAA1IAAAAJGE1MjRhZmQyLWE5N2QtNDUyMC04MWM5LTg5NTNlMjhmYjlmZA.png',
    detailUrl: 'Digital Media Software Engineering Internship, DATG (CA) - Summer 2018' },
  { job: 'Software Development Engineer - Internship',
    company: 'Audible, Inc.',
    location: 'Newark, NJ, US',
    postDateRaw: '24d',
    postDate: 2017-12-10T22:51:24.644Z,
    source: 'linkedin',
    desc: 'Proven experience as an innovator and a creator, with strong critical thinking and communication skills. We have internships in Newark, NJ, Cambridge, MA, and Seattle, WA. us-amazon.icims.com',
    identifier: '2079560da01042e04a1d889277b07bef',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAANjAAAAJDk2ZGE4YzBkLTY3ODktNGM1YS1iNTQxLTgwMDg5ZThmZjdkZA.png',
    detailUrl: 'Software Development Engineer - Internship' },
  { job: 'Software Engineer- 2018 Summer internship',
    company: 'Motorola Solutions',
    location: 'Chicago, Illinois',
    postDateRaw: '21d',
    postDate: 2017-12-13T22:51:24.644Z,
    source: 'linkedin',
    desc: 'Seeking local candidates who are strong in   Server-side web development using Node Js. Experience defining and building Web (REST) APIs for internal and external usage.',
    identifier: 'e3095218a3baed4d3e98c1ad69c1fa1a',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAUXAAAAJGFiZTYwZDVmLTM0NDYtNDM1Mi1iN2NlLTY3MmExY2M2MmIxZg.png',
    detailUrl: 'Software Engineer- 2018 Summer internship' },
  { job: 'INTERN Software Engineer/Computer Engineer',
    company: 'Raven Industries',
    location: 'Austin, TX, US',
    postDateRaw: '19d',
    postDate: 2017-12-15T22:51:24.644Z,
    source: 'linkedin',
    desc: 'Raven Industries is currently seeking a Software/Computer Engineer Intern for our facility in Austin, TX. Complete specified projects and tasks within internship or co-op period. neuvoo.com',
    identifier: 'c952e11a3f3393cdb6e690fd72ac4801',
    logoUrl: 'https://media-exp2.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAgAAAAAJDcyZGFkNjg1LWNhNzQtNGU0NS1hZjRmLTNlNGQ0MDg0MGEwMw.png',
    detailUrl: 'INTERN Software Engineer/Computer Engineer' } ]
}